export const SEASON = {
  year: 2026,
  rounds: 24,
  sprintWeekends: 6,
  teams: 11,
  drivers: 22,
};

export const TESTING_SESSIONS = [
  {
    name: "Pre-Season Testing 1",
    location: "Bahrain International Circuit, Sakhir",
    start: "2026-02-11",
    end: "2026-02-13",
  },
  {
    name: "Pre-Season Testing 2",
    location: "Bahrain International Circuit, Sakhir",
    start: "2026-02-18",
    end: "2026-02-20",
  },
];

export const RACES_2026 = [
  {
    round: 1,
    grandPrix: "Australian Grand Prix",
    city: "Melbourne",
    country: "Australia",
    circuit: "Albert Park Grand Prix Circuit",
    start: "2026-03-06",
    end: "2026-03-08",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 2,
    grandPrix: "Chinese Grand Prix",
    city: "Shanghai",
    country: "China",
    circuit: "Shanghai International Circuit",
    start: "2026-03-13",
    end: "2026-03-15",
    sprint: true,
    raceStartLocal: "15:00",
  },
  {
    round: 3,
    grandPrix: "Japanese Grand Prix",
    city: "Suzuka",
    country: "Japan",
    circuit: "Suzuka Circuit",
    start: "2026-03-27",
    end: "2026-03-29",
    sprint: false,
    raceStartLocal: "14:00",
  },
  {
    round: 4,
    grandPrix: "Bahrain Grand Prix",
    city: "Sakhir",
    country: "Bahrain",
    circuit: "Bahrain International Circuit",
    start: "2026-04-10",
    end: "2026-04-12",
    sprint: false,
    raceStartLocal: "18:00",
  },
  {
    round: 5,
    grandPrix: "Saudi Arabian Grand Prix",
    city: "Jeddah",
    country: "Saudi Arabia",
    circuit: "Jeddah Corniche Circuit",
    start: "2026-04-17",
    end: "2026-04-19",
    sprint: false,
    raceStartLocal: "20:00",
  },
  {
    round: 6,
    grandPrix: "Miami Grand Prix",
    city: "Miami",
    country: "United States",
    circuit: "Miami International Autodrome",
    start: "2026-05-01",
    end: "2026-05-03",
    sprint: true,
    raceStartLocal: "16:00",
  },
  {
    round: 7,
    grandPrix: "Canadian Grand Prix",
    city: "Montreal",
    country: "Canada",
    circuit: "Circuit Gilles Villeneuve",
    start: "2026-05-22",
    end: "2026-05-24",
    sprint: true,
    raceStartLocal: "16:00",
  },
  {
    round: 8,
    grandPrix: "Monaco Grand Prix",
    city: "Monaco",
    country: "Monaco",
    circuit: "Circuit de Monaco",
    start: "2026-06-05",
    end: "2026-06-07",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 9,
    grandPrix: "Spanish Grand Prix",
    city: "Barcelona-Catalunya",
    country: "Spain",
    circuit: "Circuit de Barcelona-Catalunya",
    start: "2026-06-12",
    end: "2026-06-14",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 10,
    grandPrix: "Austrian Grand Prix",
    city: "Spielberg",
    country: "Austria",
    circuit: "Red Bull Ring",
    start: "2026-06-26",
    end: "2026-06-28",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 11,
    grandPrix: "British Grand Prix",
    city: "Silverstone",
    country: "Great Britain",
    circuit: "Silverstone Circuit",
    start: "2026-07-03",
    end: "2026-07-05",
    sprint: true,
    raceStartLocal: "15:00",
  },
  {
    round: 12,
    grandPrix: "Belgian Grand Prix",
    city: "Spa-Francorchamps",
    country: "Belgium",
    circuit: "Circuit de Spa-Francorchamps",
    start: "2026-07-17",
    end: "2026-07-19",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 13,
    grandPrix: "Hungarian Grand Prix",
    city: "Budapest",
    country: "Hungary",
    circuit: "Hungaroring",
    start: "2026-07-24",
    end: "2026-07-26",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 14,
    grandPrix: "Dutch Grand Prix",
    city: "Zandvoort",
    country: "Netherlands",
    circuit: "Circuit Zandvoort",
    start: "2026-08-21",
    end: "2026-08-23",
    sprint: true,
    raceStartLocal: "15:00",
  },
  {
    round: 15,
    grandPrix: "Italian Grand Prix",
    city: "Monza",
    country: "Italy",
    circuit: "Autodromo Nazionale Monza",
    start: "2026-09-04",
    end: "2026-09-06",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 16,
    grandPrix: "Spanish Grand Prix",
    city: "Madrid",
    country: "Spain",
    circuit: "Madring (homologation pending)",
    start: "2026-09-11",
    end: "2026-09-13",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 17,
    grandPrix: "Azerbaijan Grand Prix",
    city: "Baku",
    country: "Azerbaijan",
    circuit: "Baku City Circuit",
    start: "2026-09-24",
    end: "2026-09-26",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 18,
    grandPrix: "Singapore Grand Prix",
    city: "Singapore",
    country: "Singapore",
    circuit: "Marina Bay Street Circuit",
    start: "2026-10-09",
    end: "2026-10-11",
    sprint: true,
    raceStartLocal: "20:00",
  },
  {
    round: 19,
    grandPrix: "United States Grand Prix",
    city: "Austin",
    country: "United States",
    circuit: "Circuit of The Americas",
    start: "2026-10-23",
    end: "2026-10-25",
    sprint: false,
    raceStartLocal: "15:00",
  },
  {
    round: 20,
    grandPrix: "Mexico City Grand Prix",
    city: "Mexico City",
    country: "Mexico",
    circuit: "Autodromo Hermanos Rodriguez",
    start: "2026-10-30",
    end: "2026-11-01",
    sprint: false,
    raceStartLocal: "14:00",
  },
  {
    round: 21,
    grandPrix: "Sao Paulo Grand Prix",
    city: "Interlagos",
    country: "Brazil",
    circuit: "Interlagos Circuit",
    start: "2026-11-06",
    end: "2026-11-08",
    sprint: false,
    raceStartLocal: "14:00",
  },
  {
    round: 22,
    grandPrix: "Las Vegas Grand Prix",
    city: "Las Vegas",
    country: "United States",
    circuit: "Las Vegas Strip Circuit",
    start: "2026-11-19",
    end: "2026-11-21",
    sprint: false,
    raceStartLocal: "20:00",
  },
  {
    round: 23,
    grandPrix: "Qatar Grand Prix",
    city: "Lusail",
    country: "Qatar",
    circuit: "Lusail International Circuit",
    start: "2026-11-27",
    end: "2026-11-29",
    sprint: false,
    raceStartLocal: "19:00",
  },
  {
    round: 24,
    grandPrix: "Abu Dhabi Grand Prix",
    city: "Yas Marina",
    country: "United Arab Emirates",
    circuit: "Yas Marina Circuit",
    start: "2026-12-04",
    end: "2026-12-06",
    sprint: false,
    raceStartLocal: "17:00",
  },
];

export const TEAMS_2026 = [
  {
    name: "McLaren Mastercard F1 Team",
    base: "Woking, United Kingdom",
    powerUnit: "Mercedes",
    drivers: ["Lando Norris", "Oscar Piastri"],
  },
  {
    name: "Mercedes-AMG PETRONAS Formula One Team",
    base: "Brackley, United Kingdom",
    powerUnit: "Mercedes",
    drivers: ["George Russell", "Andrea Kimi Antonelli"],
  },
  {
    name: "Oracle Red Bull Racing",
    base: "Milton Keynes, United Kingdom",
    powerUnit: "Red Bull Ford Powertrains",
    drivers: ["Max Verstappen", "Isack Hadjar"],
  },
  {
    name: "Scuderia Ferrari HP",
    base: "Maranello, Italy",
    powerUnit: "Ferrari",
    drivers: ["Charles Leclerc", "Lewis Hamilton"],
  },
  {
    name: "Atlassian Williams F1 Team",
    base: "Grove, United Kingdom",
    powerUnit: "Mercedes",
    drivers: ["Alexander Albon", "Carlos Sainz"],
  },
  {
    name: "Visa Cash App Racing Bulls Formula One Team",
    base: "Faenza, Italy",
    powerUnit: "Red Bull Ford Powertrains",
    drivers: ["Arvid Lindblad", "Liam Lawson"],
  },
  {
    name: "Aston Martin Aramco Formula One Team",
    base: "Silverstone, United Kingdom",
    powerUnit: "Honda",
    drivers: ["Lance Stroll", "Fernando Alonso"],
  },
  {
    name: "TGR Haas F1 Team",
    base: "Kannapolis, United States / Banbury, United Kingdom",
    powerUnit: "Ferrari",
    drivers: ["Esteban Ocon", "Oliver Bearman"],
  },
  {
    name: "Audi Revolut F1 Team",
    base: "Hinwil, Switzerland",
    powerUnit: "Audi",
    drivers: ["Nico Hulkenberg", "Gabriel Bortoleto"],
  },
  {
    name: "BWT Alpine Formula One Team",
    base: "Enstone, United Kingdom / Viry-Chatillon, France",
    powerUnit: "Alpine",
    drivers: ["Pierre Gasly", "Franco Colapinto"],
  },
  {
    name: "Cadillac Formula 1 Team",
    base: "United States and United Kingdom operations",
    powerUnit: "Not yet publicly confirmed",
    drivers: ["Sergio Perez", "Valtteri Bottas"],
  },
];

export const DRIVERS_2026 = [
  { name: "Lando Norris", nationality: "United Kingdom", team: "McLaren Mastercard F1 Team" },
  { name: "Oscar Piastri", nationality: "Australia", team: "McLaren Mastercard F1 Team" },
  { name: "George Russell", nationality: "United Kingdom", team: "Mercedes-AMG PETRONAS Formula One Team" },
  { name: "Andrea Kimi Antonelli", nationality: "Italy", team: "Mercedes-AMG PETRONAS Formula One Team" },
  { name: "Max Verstappen", nationality: "Netherlands", team: "Oracle Red Bull Racing" },
  { name: "Isack Hadjar", nationality: "France", team: "Oracle Red Bull Racing" },
  { name: "Charles Leclerc", nationality: "Monaco", team: "Scuderia Ferrari HP" },
  { name: "Lewis Hamilton", nationality: "United Kingdom", team: "Scuderia Ferrari HP" },
  { name: "Alexander Albon", nationality: "Thailand", team: "Atlassian Williams F1 Team" },
  { name: "Carlos Sainz", nationality: "Spain", team: "Atlassian Williams F1 Team" },
  { name: "Arvid Lindblad", nationality: "United Kingdom", team: "Visa Cash App Racing Bulls Formula One Team" },
  { name: "Liam Lawson", nationality: "New Zealand", team: "Visa Cash App Racing Bulls Formula One Team" },
  { name: "Lance Stroll", nationality: "Canada", team: "Aston Martin Aramco Formula One Team" },
  { name: "Fernando Alonso", nationality: "Spain", team: "Aston Martin Aramco Formula One Team" },
  { name: "Esteban Ocon", nationality: "France", team: "TGR Haas F1 Team" },
  { name: "Oliver Bearman", nationality: "United Kingdom", team: "TGR Haas F1 Team" },
  { name: "Nico Hulkenberg", nationality: "Germany", team: "Audi Revolut F1 Team" },
  { name: "Gabriel Bortoleto", nationality: "Brazil", team: "Audi Revolut F1 Team" },
  { name: "Pierre Gasly", nationality: "France", team: "BWT Alpine Formula One Team" },
  { name: "Franco Colapinto", nationality: "Argentina", team: "BWT Alpine Formula One Team" },
  { name: "Sergio Perez", nationality: "Mexico", team: "Cadillac Formula 1 Team" },
  { name: "Valtteri Bottas", nationality: "Finland", team: "Cadillac Formula 1 Team" },
];

export const REGULATION_FACTS_2026 = [
  {
    title: "Smaller Footprint",
    detail:
      "Maximum wheelbase reduces to 3400 mm and maximum width to 1900 mm to improve agility and raceability.",
  },
  {
    title: "Lower Minimum Mass",
    detail: "Minimum car weight target is reduced by 30 kg to 768 kg.",
  },
  {
    title: "New Power Unit Balance",
    detail:
      "MGU-H is removed and MGU-K output increases to 350 kW under the 2026 PU framework.",
  },
  {
    title: "100% Advanced Sustainable Fuel",
    detail:
      "The 2026 regulations continue Formula 1's move to fully advanced sustainable fuel in race conditions.",
  },
  {
    title: "Active Aero Concept",
    detail:
      "Cars use multiple aerodynamic modes, including high-downforce and low-drag states, to support overtaking and efficiency.",
  },
  {
    title: "Sprint Format Continues",
    detail:
      "Six sprint weekends are officially scheduled: China, Miami, Canada, Great Britain, Netherlands, and Singapore.",
  },
];

export const SOURCES = [
  {
    label: "Formula1.com 2026 race calendar",
    url: "https://www.formula1.com/en/racing/2026",
  },
  {
    label: "Formula 1 reveals 2026 calendar (official article)",
    url: "https://www.formula1.com/en/latest/article/formula-1-reveals-calendar-for-2026-season.YctbMZWqBvrgyddrnauo8",
  },
  {
    label: "Formula 1 and FIA announce 2026 Sprint Calendar",
    url: "https://www.formula1.com/en/latest/article/formula-1-and-fia-announce-2026-sprint-calendar.3PyLPAazrBNe8kQIS3wOfY",
  },
  {
    label: "Official 2026 Grand Prix start times",
    url: "https://www.formula1.com/en/latest/article/official-grand-prix-start-times-for-2026-f1-season-confirmed.2UgPfArqH76tzlOYh21jSG",
  },
  {
    label: "FIA 2026 entry list",
    url: "https://www.fia.com/events/fia-formula-one-world-championship/season-2026/2026-fia-formula-one-world-championship-entry",
  },
  {
    label: "FIA 2026 regulations overview",
    url: "https://www.fia.com/news/fia-unveils-2026-f1-regulations-breakthrough-car-concept-closer-racing-and-improved",
  },
];
